name: Build Windows Binary

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install additional target
        run: rustup target add ${{ matrix.target }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: npm install

      - name: Build Ostler
        run: npm run tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ostler-macos-${{ matrix.target }}
          path: |
            src-tauri/target/${{ matrix.target }}/release/dmg/*.dmg
